### PR TITLE
update tkinter gui using tkk

### PR DESCRIPTION
**Pull request by rusty-electron**
## list-of-changes
* update tkinter widgets to ttk widgets
* update `linux` and `windows` gui styling
* fix typos from previous commit

### before:

linux - before
win-before

### now:

linux - now
win-after

### CODE REVIEW

**Comment by s-ankur** [comment]
Great work! i though about doing this but it kinda breaks on my desktop environment (kde)

**Comment by s-ankur** [comment]
Also, if you have the time, you should update the gifs when this is merged so that it will be more accurate

**Comment by rusty-electron** [comment]
I have tested it on ubuntu and windows only. Don't know about kde though. 

Yeah, I'll add updated gifs soon.

**Comment by rusty-electron** [comment]
not merged?

**Comment by rusty-electron** [comment]
@s-ankur does this work well in kde?

**Comment by s-ankur** [comment]
Yes now it works fine. This should be merged

**Pull request closed without merging**
